import { MessageV2 } from "@/session/message-v2"
import type { PermissionReviewerPrompt } from "./prompt"

const ENTRY_LIMIT = 40
const PART_CHAR_LIMIT = 4000
const ENTRY_CHAR_LIMIT = 1000
// 用户消息是授权证据的主要来源；长指令 + 末尾授权（如 "## 创建 commit"）
// 可能超过 1000 字符。给用户消息更大预算，减少末尾授权被截断的概率。
// worst case 40 × 2000 = 80k 字符，是旧 40 × 1000 = 40k 的 2 倍，
// 对任何 ≥128k context 的 reviewer 模型是安全的。
const ENTRY_CHAR_LIMIT_USER = 2000
type RenderedEntry = PermissionReviewerPrompt.TranscriptEntry & { truncated: boolean }

export function fromMessages(messages: readonly MessageV2.WithParts[]): PermissionReviewerPrompt.TranscriptDelta {
  // Codex-style review context keeps user intent anchors plus recent tool
  // evidence instead of blindly sending the last N messages. The first user turn
  // often contains the original authorization, while the latest turns explain
  // retries and current scope; preserving both keeps context useful without
  // expanding reviewer input cost.
  const visibleMessages = messages.filter((message) => !message.info.hidden)
  const rendered = visibleMessages.map((message) => {
      const text = message.parts.map(renderPart).filter((part): part is string => Boolean(part?.trim())).join("\n")
      // 用户消息使用更大预算并保留尾部：授权指令常出现在长消息末尾，
      // 只保留头部会丢失尾部授权证据导致 reviewer fail-closed 误拒。
      // 非用户消息保持原有 1000 字符头部截断，避免作用域蔓延到 tool 输出。
      const isUser = message.info.role === "user"
      const entry = truncateWithFlag(text, isUser ? ENTRY_CHAR_LIMIT_USER : ENTRY_CHAR_LIMIT, isUser)
      return {
        role: message.info.role,
        text: entry.text,
        truncated: entry.truncated,
      }
    })
  const visibleRendered = rendered.filter((entry) => entry.text.trim())
  const entries = selectEntries(visibleRendered)
  return {
    entries: entries.items.map((entry) => ({ role: entry.role, text: entry.text })),
    truncated: entries.truncated,
    entryTruncated: entries.items.some((entry) => entry.truncated),
    emptyEntries: visibleMessages.length > visibleRendered.length,
  }
}

function selectEntries(entries: readonly RenderedEntry[]) {
  if (entries.length <= ENTRY_LIMIT) return { items: entries, truncated: false }
  const keep = new Set<number>()
  const userIndexes = entries.flatMap((entry, index) => (entry.role === "user" ? [index] : []))
  if (userIndexes[0] !== undefined) keep.add(userIndexes[0])
  const latestUserIndex = userIndexes.at(-1)
  if (latestUserIndex !== undefined) keep.add(latestUserIndex)
  for (let index = entries.length - 1; index >= 0 && keep.size < ENTRY_LIMIT; index--) {
    keep.add(index)
  }
  return {
    items: Array.from(keep)
      .sort((left, right) => left - right)
      .map((index) => entries[index]),
    truncated: true,
  }
}

function renderPart(part: MessageV2.Part) {
  // Hidden, synthetic, and reasoning parts are not user authorization evidence.
  // This mirrors Codex guardian: review sees visible conversation plus tool
  // evidence, not internal thinking or generated scaffolding that can make the
  // reviewer over-trust the agent's own rationale.
  if (part.hidden) return ""
  if (part.type === "text" && part.synthetic) return ""
  // Reviewer child-session request cells are visible for audit/navigation, but
  // they are protocol records generated by opencode, not fresh user approval.
  // Exclude them if a future incremental review ever projects the reviewer
  // child transcript back into another review request.
  if (part.type === "text" && part.metadata?.permissionReviewerRequest === true) return ""
  if (part.type === "reasoning") return ""
  if (part.type === "text") return truncate(part.text)
  if (part.type === "tool") return renderTool(part)
  if (part.type === "file") return `<file mime="${part.mime}" filename="${part.filename ?? ""}" />`
  if (part.type === "subtask") return `<subtask agent="${part.agent}" description="${truncate(part.description, 400)}" />`
  if (part.type === "patch") return `<patch files="${part.files.join(",")}" />`
  if (part.type === "agent") return `<agent name="${part.name}" />`
  return `<${part.type} />`
}

function renderTool(part: MessageV2.ToolPart) {
  // Tool state is evidence, not instructions. Include input/output summaries for
  // completed tools and raw pending input for unresolved calls, each bounded by
  // truncate() to avoid unbounded reviewer context.
  if (part.state.status === "pending") return `<tool name="${part.tool}" status="pending">${truncate(part.state.raw)}</tool>`
  if (part.state.status === "running") {
    return `<tool name="${part.tool}" status="running">${truncate(JSON.stringify(part.state.input))}</tool>`
  }
  if (part.state.status === "completed") {
    return `<tool name="${part.tool}" status="completed" title="${part.state.title}">\ninput=${truncate(JSON.stringify(part.state.input))}\noutput=${truncate(part.state.output)}\n</tool>`
  }
  return `<tool name="${part.tool}" status="error">${truncate(part.state.error)}</tool>`
}

function truncate(text: string, limit = PART_CHAR_LIMIT) {
  // truncate 用于 part/tool 输出截断，不保留尾部：tool 输出的尾部截断
  // 不是授权证据丢失问题，保持原有行为避免作用域蔓延
  return truncateWithFlag(text, limit, false).text
}

function truncateWithFlag(text: string, limit = PART_CHAR_LIMIT, preserveTail = false) {
  // The marker records exactly how much was omitted so policy can treat missing
  // evidence conservatively instead of assuming the hidden tail was benign.
  if (text.length <= limit) return { text, truncated: false }
  if (preserveTail) {
    // 头尾保留：头部 60% 提供上下文，尾部 40% 保留末尾授权证据。
    // 截断标记位于中间，chars 仍精确等于被省略的字符数。
    const head = Math.floor(limit * 0.6)
    const tail = limit - head
    return {
      text: text.slice(0, head) + `\n<truncated chars="${text.length - limit}" />\n` + text.slice(text.length - tail),
      truncated: true,
    }
  }
  return { text: text.slice(0, limit) + `\n<truncated chars="${text.length - limit}" />`, truncated: true }
}

export * as PermissionReviewerTranscript from "./transcript"
